In [1]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_excel('Test.xlsx')
data.columns = data.columns.str.strip()

In [ ]:
pd.set_option('display.max_columns', None)

In [85]:
data.describe()

,Date,Opening Weights,Open Quantity,Close Quantity,Closing Weights,Price,Exchange Rate,Value in USD,Price Yesterday,Stock Movement,Performance Contribution,Traded Today,Trade Price,Trade Day Move,Trade Weight,Return Adjustments,Total Return,Calculated NAV,NAV Yesterday,Close Weight ABS,Dollar PnL,SharesOut,Market_Cap
count,7721,"7,721.0000","7,721.0000","7,721.0000","7,721.0000","7,721.0000","7,721.0000","7,721.0000","7,721.0000","7,721.0000","7,721.0000","1,644.0000","1,644.0000","1,644.0000","1,644.0000","1,644.0000","7,721.0000","7,721.0000","7,721.0000","7,721.0000","7,721.0000","7,721.0000","7,721.0000"
mean,2022-07-24 21:10:39.243621376,0.0129,"3,068.1034","3,076.4218",0.0131,139.4934,0.9125,"16,490.2404",139.6587,-0.0011,0.0000,39.0675,149.7213,0.0011,-0.0001,0.0001,0.0001,"1,253,227.9719","1,254,114.3091",0.0463,62.5153,"4,898,624.9684","268,324,181.2121"
min,2022-01-03 00:00:00,-0.8577,"-575,000.0000","-575,000.0000",-0.8404,0.3480,0.0072,"-1,058,781.4614",0.3480,-0.4292,-0.0205,"-600,000.0000",0.3824,-0.2735,-1.0160,-0.0240,-0.0240,"880,246.2748","875,350.4375",0.0000,"-35,086.3430",1.4372,220.8729
25%,2022-05-02 00:00:00,-0.0199,-571.0000,-571.0000,-0.0200,14.5300,1.0000,"-25,332.1611",14.5300,-0.0171,-0.0004,-861.2500,22.2816,-0.0106,-0.0294,-0.0002,-0.0005,"1,167,916.7169","1,164,112.5000",0.0198,-613.0790,125.8000,"3,495.0433"
50%,2022-08-09 00:00:00,0.0197,184.0000,185.0000,0.0196,42.4300,1.0000,"23,663.1995",42.5400,0.0000,0.0000,2.0000,54.6098,-0.0001,0.0002,0.0000,0.0000,"1,297,075.1959","1,308,857.1250",0.0313,0.0000,442.8000,"13,949.4853"
75%,2022-10-21 00:00:00,0.0433,"1,690.0000","1,718.0000",0.0434,120.5250,1.0000,"53,092.7998",120.9600,0.0149,0.0004,865.2500,145.3302,0.0105,0.0294,0.0003,0.0005,"1,363,641.6667","1,364,549.3750",0.0502,615.8666,"3,584.4621","81,558.7165"
max,2022-12-29 00:00:00,1.0213,"690,000.0000","690,000.0000",1.0505,"4,798.2500",1.1451,"1,356,711.8016","4,920.7500",0.3408,0.0361,"600,000.0000","4,848.5490",0.3647,0.9734,0.0355,0.0361,"1,540,782.3846","1,490,785.8750",1.0505,"45,916.0368","390,458,000.0000","14,630,693,000.0000"
std,NaN,0.0881,"38,129.6773","38,137.9895",0.0886,338.4122,0.2827,"116,345.9043",338.9141,0.0384,0.0017,"23,812.6211",334.4354,0.0344,0.0958,0.0021,0.0019,"153,640.9774","156,494.7521",0.0767,"2,345.6534","30,846,217.5426","1,683,322,095.3336"

In [ ]:
data.head()

,Date,P_Ticker,Short_Name,Opening Weights,Open Quantity,Close Quantity,Closing Weights,Currency,Price,Exchange Rate,Value in USD,Price Yesterday,Stock Movement,Performance Contribution,Traded Today,Trade Price,Trade Day Move,Trade Weight,Return Adjustments,Total Return,Calculated NAV,NAV Yesterday,Country,Sector,Industry,Sub_Ind,IS_Currency,Close Weight ABS,IS_Future,Short_Pos,Dollar PnL,SharesOut,Market_Cap,Cap Class
0,2022-01-03,ADBE,ADOBE INC,0.0240,39,39,0.0237,USD,564.2500,1.0000,"22,005.7500",567.2400,-0.0053,-0.0001,NaN,NaN,NaN,NaN,NaN,-0.0001,"929,315.6228","921,929.6875",US,Information Technology,Software,Application Software,False,0.0237,False,False,-116.6096,448.0000,"252,784.0000",Mega
1,2022-01-03,ADE,Bitcoin Group SE,0.0194,387,387,0.0194,EURUSD,41.2500,1.1297,"18,034.2475",40.8500,0.0098,0.0002,NaN,NaN,NaN,NaN,NaN,0.0002,"929,315.6228","921,929.6875",DE,Financials,Capital Markets,Crypto,False,0.0194,False,False,174.8782,5.0000,233.0006,Micro
2,2022-01-03,ADI,ANALOG DEVICES,0.0532,279,279,0.0532,USD,177.1150,1.0000,"49,415.0865",175.8200,0.0074,0.0004,NaN,NaN,NaN,NaN,NaN,0.0004,"929,315.6228","921,929.6875",US,Information Technology,Semiconductors & Semiconductor,Semiconductors,False,0.0532,False,False,361.3045,495.9081,"87,832.7747",Large
3,2022-01-03,AMAT,APPLIED MATERIAL,0.0237,139,139,0.0239,USD,159.9250,1.0000,"22,229.5754",157.3450,0.0164,0.0004,NaN,NaN,NaN,NaN,NaN,0.0004,"929,315.6228","921,929.6875",US,Information Technology,Semiconductors & Semiconductor,Semiconductor Equipment,False,0.0239,False,False,358.6203,830.0000,"132,737.7525",Large
4,2022-01-03,AMC,AMC ENTERTAINMEN,-0.0066,-224,-224,-0.0064,USD,26.5250,1.0000,"-5,941.5999",27.2050,-0.0250,0.0002,NaN,NaN,NaN,NaN,NaN,0.0002,"929,315.6228","921,929.6875",US,Communication Services,Entertainment,Movies & Entertainment,False,0.0064,False,True,152.3201,295.5878,"7,840.4650",SMID

### Check Exchange Rate Ranges

This cell defines a function `check_exchange_rate_ranges` to validate whether the exchange rates for different currencies fall within predefined reasonable ranges. It flags rows where the exchange rate is outside the expected range and returns a DataFrame containing the flagged rows.

In [ ]:
def check_exchange_rate_ranges(data):
    currency_ranges = {
        'USD': (1, 1),
        'EURUSD': (0.95, 1.2),
        'GBPUSD': (1.20, 1.45),
        'HKDUSD': (0.127, 0.129),
        'CADUSD': (0.69, 0.83),
        'SEKUSD': (0.087, 0.125),
        'CHFUSD': (0.91, 1.18),
        'JPYUSD': (0.0063, 0.0111),
        'PLNUSD': (0.22, 0.31)
    }
    
    data['Exchange Rate Error'] = data.apply(
        lambda row: not (currency_ranges[row['Currency']][0] <= row['Exchange Rate'] <= currency_ranges[row['Currency']][1])
        if row['Currency'] in currency_ranges else False,
        axis=1
    )
    exchange_rate_errors = data[data['Exchange Rate Error']]
    
    return exchange_rate_errors[['Date', 'P_Ticker', 'Currency', 'Exchange Rate', 'Exchange Rate Error']]

# Example usage
exchange_rate_errors = check_exchange_rate_ranges(data)
exchange_rate_errors

           Date P_Ticker Currency  Exchange Rate  Exchange Rate Error
6    2022-01-03     ANTO   GBPUSD         0.0135                 True
27   2022-01-04     ANTO   GBPUSD         0.0135                 True
46   2022-01-05     ANTO   GBPUSD         0.0136                 True
65   2022-01-06     ANTO   GBPUSD         0.0135                 True
82   2022-01-07     ANTO   GBPUSD         0.0136                 True
...         ...      ...      ...            ...                  ...
7634 2022-12-27      TGA   GBPUSD         0.0115                 True
7643 2022-12-28     ANTO   GBPUSD         0.0115                 True
7675 2022-12-28      TGA   GBPUSD         0.0115                 True
7684 2022-12-29     ANTO   GBPUSD         0.0115                 True
7715 2022-12-29      TGA   GBPUSD         0.0115                 True

[344 rows x 5 columns]

### Check for quantity change errors

This function, `check_quantity_trade_mismatch`, identifies discrepancies between the change in holding quantities (`Open Quantity` and `Close Quantity`) and the reported trades (`Traded Today`). It calculates the `Quantity Change` as the difference between `Close Quantity` and `Open Quantity`. Rows where the `Quantity Change` is non-zero but does not match the `Traded Today` value (within a small numerical tolerance, `atol=1e-6`) are flagged.

In [182]:
def check_quantity_trade_mismatch(data):
    data['Quantity Change'] = data['Close Quantity'] - data['Open Quantity']
    quantity_flags = data[
        (data['Quantity Change'] != 0) & 
        (~np.isclose(data['Traded Today'], data['Quantity Change'], atol=1e-6))
    ]
    return quantity_flags[['Date', 'P_Ticker', 'Open Quantity', 'Close Quantity', 'Quantity Change', 'Traded Today']]

# Example usage
quantity_flags = check_quantity_trade_mismatch(data)
quantity_flags

Empty DataFrame
Columns: [Date, P_Ticker, Open Quantity, Close Quantity, Quantity Change, Traded Today]
Index: []

### Check Prices where changes are greater than 10 percent compared to yesterdays price

This cell defines a function `check_inconsistent_prices` to identify rows in the dataset where the percentage change in price exceeds a specified threshold (10% in this case). It calculates the price change and the percentage change relative to the previous day's price, flags rows with significant changes, and returns a DataFrame containing the flagged rows.

In [ ]:
def check_inconsistent_prices(data):
    data['Price Change'] = data['Price'] - data['Price Yesterday']
    data['Price Change Percentage'] = data['Price Change'] / data['Price Yesterday']
    price_flags = data[np.abs(data['Price Change Percentage']) > 0.1]  # Flagging >10% change
    return price_flags[['Date', 'P_Ticker', 'Price', 'Price Yesterday', 'Price Change Percentage']]

# Example usage
price_flags = check_inconsistent_prices(data)
price_flags

           Date P_Ticker    Price  Price Yesterday  Price Change Percentage
33   2022-01-04       SE 197.8350         223.1850                  -0.1136
44   2022-01-05      AMC  22.7450          25.4950                  -0.1079
49   2022-01-05      GME 129.3350         148.6050                  -0.1297
53   2022-01-05     RIVN  90.0200         101.4350                  -0.1125
139  2022-01-12      TMV  13.4750          11.6725                   0.1544
...         ...      ...      ...              ...                      ...
7366 2022-12-19     MARA   3.8700           4.7200                  -0.1801
7374 2022-12-19     PALL 154.2500         177.9200                  -0.1330
7619 2022-12-27     MARA   3.2400           3.6200                  -0.1050
7636 2022-12-27     TSLA 109.1000         123.1500                  -0.1141
7689 2022-12-29     CVNA   4.4500           3.8300                   0.1619

[184 rows x 5 columns]

Similarly for trade price

In [ ]:
def check_trade_price_vs_price_today(data):
    data['Trade Price Change Percentage'] = np.abs(data['Trade Price'] - data['Price']) / data['Price']
    trade_price_flags = data[data['Trade Price Change Percentage'] > 0.1]  # Flagging >10% change
    return trade_price_flags[['Date', 'P_Ticker', 'Price', 'Trade Price', 'Trade Price Change Percentage']]

# Example usage
trade_price_flags = check_trade_price_vs_price_today(data)
trade_price_flags

           Date P_Ticker    Price  Trade Price  Trade Price Change Percentage
710  2022-03-02      RSX   7.1900       8.1300                         0.1307
806  2022-03-07     RIVN  42.4300      48.0000                         0.1313
807  2022-03-08   CLB_US  35.0400      31.4088                         0.1036
844  2022-03-09     HSBK   9.4450       8.5000                         0.1001
845  2022-03-09      KAP  26.5500      32.8411                         0.2370
846  2022-03-09     KSPI  48.6000      39.6500                         0.1842
1781 2022-04-21      NXE   6.0100       5.4015                         0.1013
2054 2022-05-09     MSTR 219.2550     253.0000                         0.1539
2105 2022-05-11     MSTR 168.2450     202.0000                         0.2006
2482 2022-06-01     CVNA  26.4950      29.6471                         0.1190
3078 2022-06-28     CVNA  24.7350      28.4300                         0.1494
4179 2022-08-22      AMC  10.4600      12.6000                         0.2046
4261 2022-08-24      AMC   9.5800       7.0200                         0.2672
5022 2022-09-15   SSL_CA   7.3700       8.2766                         0.1230
5357 2022-09-29      VNA  26.3650      21.3200                         0.1914
5382 2022-09-30      VNA  26.3650      21.2600                         0.1936
5383 2022-10-03      DBK   8.3255       7.3622                         0.1157
5391 2022-10-03     GLTL  43.7200      48.8001                         0.1162
5414 2022-10-04       LI  18.5275      25.5011                         0.3764
5495 2022-10-07     GLTL  39.6700      46.8481                         0.1809
5496 2022-10-07       LI  17.7950      20.3065                         0.1411
5519 2022-10-07      VNA  26.3650      21.1015                         0.1996
5593 2022-10-13     MARA  11.2200       9.5300                         0.1506
5683 2022-10-17      VNA  26.3650      21.2061                         0.1957
5860 2022-10-24      VNA  26.3650      21.1340                         0.1984
5892 2022-10-25      VNA  26.3650      22.2100                         0.1576
6007 2022-10-28      VNA  26.3650      22.4843                         0.1472
6008 2022-10-31      CLF  16.8100      13.0812                         0.2218
7213 2022-12-14     EXS1 111.2900     123.7129                         0.1116
7291 2022-12-16     MARA   4.7200       3.9802                         0.1567
7292 2022-12-16       SE  64.9800      55.5034                         0.1458

### Calculate and Check Profit Errors

This cell defines a function `calculate_and_check_profit_errors` to calculate the Dollar Profit and Loss (PnL) based on each row of data and including if a trade has been carried out and compare it with the existing Dollar PnL values. It flags rows where the calculated Dollar PnL does not match the existing Dollar PnL within a specified tolerance.

In [ ]:
def calculate_and_check_profit_errors(data):
    # Calculate Dollar PnL
    data['Calculated Dollar PnL'] = np.where(
        data['Open Quantity'] == data['Close Quantity'],
        (data['Price'] - data['Price Yesterday']) * data['Close Quantity'] * data['Exchange Rate'],
        np.where(
            data['Close Quantity'] > data['Open Quantity'],
            data['Open Quantity'] * (data['Price'] - data['Price Yesterday']) * data['Exchange Rate'] - 
            (data['Close Quantity'] - data['Open Quantity']) * (data['Trade Price'] - data['Price']) * data['Exchange Rate'],
            (data['Open Quantity'] - data['Close Quantity']) * (data['Trade Price'] - data['Price']) * data['Exchange Rate'] +
            data['Open Quantity'] * (data['Price'] - data['Price Yesterday']) * data['Exchange Rate']
        )
    )

    hidden_flags = data[
        ~np.isclose(data['Dollar PnL'], data['Calculated Dollar PnL'], atol=1e-6)
    ]
    
    return hidden_flags[['Date', 'P_Ticker', 'Dollar PnL', 'Calculated Dollar PnL']]

# Example usage
pnl_flags = calculate_and_check_profit_errors(data)
pnl_flags

           Date P_Ticker  Dollar PnL  Calculated Dollar PnL
4221 2022-08-23      AMC    668.0864               641.8995

### Calculate Value in USD and Exchange Rate Errors

This function, `check_currency_conversion_errors`, identifies discrepancies in currency conversion calculations within a dataset. It computes the "Calculated Value in USD" for each row by multiplying the `Price`, `Exchange Rate`, and `Close Quantity`. It then compares this calculated value with the existing `Value in USD` column using a tolerance (`atol=1e-6`) to account for minor numerical differences.

In [176]:
def check_currency_conversion_errors(data):
    data['Calculated Value in USD (Currency Check)'] = data['Price'] * data['Exchange Rate'] * data['Close Quantity']
    data['Currency Conversion Error'] = ~np.isclose(data['Value in USD'], data['Calculated Value in USD (Currency Check)'], atol=1e-6)
    
    # Filter rows with currency conversion errors
    currency_conversion_errors = data[data['Currency Conversion Error']]
    return currency_conversion_errors[['Date', 'P_Ticker', 'Value in USD', 'Calculated Value in USD (Currency Check)']]

currency_conversion_errors = check_currency_conversion_errors(data)
currency_conversion_errors

,Date,P_Ticker,Value in USD,Calculated Value in USD (Currency Check)
371,2022-02-04,EXW1,"-472,104.1299",0.0000
762,2022-03-04,RHM,"121,400.2212","-94,936.9578"
792,2022-03-07,RHM,"126,674.9550","-99,061.8858"
988,2022-03-14,PFE,"25,891.6694","28,860.3400"
1853,2022-04-27,ETFMIB,"-238,910.1803",0.0000
...,...,...,...,...
7658,2022-12-28,KSPI,"58,604.0014","65,065.0000"
7684,2022-12-29,ANTO,"-66,676.9950","-86,869.7962"
7697,2022-12-29,HSBK,"40,267.3038","47,778.2008"
7698,2022-12-29,KAP,"38,692.5000","42,333.2790"
7699,2022-12-29,KSPI,"58,604.0014","65,520.0000"

### Validate Opening and Closing Weights

Given the identified discrepancies in the `Value in USD`, it is crucial to validate the accuracy of the `Opening Weights` and `Closing Weights` as they are directly dependent on the total `Value in USD`.

In [179]:
def check_weights_errors(data):
    # Calculate Opening Weights
    data['Calculated Opening Weights'] = (data['Price Yesterday'] * data['Exchange Rate'] * data['Open Quantity']) / data['NAV Yesterday']
    data['Opening Weights Error'] = ~np.isclose(data['Opening Weights'], data['Calculated Opening Weights'], atol=1e-6)

    # Calculate Closing Weights
    data['Calculated Closing Weights'] = (data['Price'] * data['Close Quantity'] * data['Exchange Rate']) / data['Calculated NAV']
    data['Closing Weights Error'] = ~np.isclose(data['Closing Weights'], data['Calculated Closing Weights'], atol=1e-6)

    # Filter rows with errors
    weights_errors = data[data['Opening Weights Error'] | data['Closing Weights Error']]
    return weights_errors[['Date', 'P_Ticker', 'Opening Weights', 'Calculated Opening Weights', 
                           'Opening Weights Error', 'Closing Weights', 'Calculated Closing Weights', 
                           'Closing Weights Error']]

# Example usage
weights_errors = check_weights_errors(data)
weights_errors

Empty DataFrame
Columns: [Date, P_Ticker, Opening Weights, Calculated Opening Weights, Opening Weights Error, Closing Weights, Calculated Closing Weights, Closing Weights Error]
Index: []

In [184]:
all_flags = pd.concat([exchange_rate_errors,quantity_flags, price_flags, trade_price_flags, pnl_flags, weights_errors, currency_conversion_errors], axis=0)
all_flags

,Date,P_Ticker,Currency,Exchange Rate,Exchange Rate Error,Open Quantity,Close Quantity,Quantity Change,Traded Today,Price,Price Yesterday,Price Change Percentage,Trade Price,Trade Price Change Percentage,Dollar PnL,Calculated Dollar PnL,Opening Weights,Calculated Opening Weights,Opening Weights Error,Closing Weights,Calculated Closing Weights,Closing Weights Error,Value in USD,Calculated Value in USD (Currency Check)
6,2022-01-03,ANTO,GBPUSD,0.0135,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2022-01-04,ANTO,GBPUSD,0.0135,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,2022-01-05,ANTO,GBPUSD,0.0136,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,2022-01-06,ANTO,GBPUSD,0.0135,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,2022-01-07,ANTO,GBPUSD,0.0136,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7658,2022-12-28,KSPI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"58,604.0014","65,065.0000"
7684,2022-12-29,ANTO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"-66,676.9950","-86,869.7962"
7697,2022-12-29,HSBK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"40,267.3038","47,778.2008"
7698,2022-12-29,KAP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"38,692.5000","42,333.2790"
7699,2022-12-29,KSPI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"58,604.0014","65,520.0000"

There are 791 flags that could potentially result in errors and thus flagged